[config]
additional_profiles = ["development", "production"]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["ffi"]
ANDROID_PLATFORM_VERSION = "28"

[tasks.test-flow]
disabled = true

[tasks.android-dev]
description = "development android x86_64 emulator"
category = "Build"
dependencies = ["android-x86_64", "android-x86_64-release"]

[tasks.android-arm]
description = "build android ARM64 for actual device"
category = "Build"
dependencies = ["android-aarch64", "android-aarch64-release"]


[tasks.build]
description = "Runs the rust compiler."
category = "Build"
dependencies = ["android"]

[tasks.build.mac]
dependencies = ["android", "ios"]

[tasks.ios]
description = "build iOS targets"
category = "Build"
dependencies = ["ios-build", "ios-release"]

[tasks.ios-build]
condition = { platforms = ["mac"], env_true = ["DEV"] }
description = "Build ios targets."
category = "Build"
command = "cargo"
args = ["lipo"]

[tasks.ios-release]
condition = { platforms = ["mac"], profiles = ["production"] }
description = "Build ios targets."
category = "Build"
command = "cargo"
args = ["lipo", "--release"]

[tasks.android]
description = "Build android targets."
category = "Build"
dependencies = [
    "android-aarch64",
    "android-aarch64-release",
    "android-armv7",
    "android-armv7-release",
    "android-i686",
    "android-i686-release",
    "android-x86_64",
    "android-x86_64-release",
]

[tasks.android-build]
private = true
condition = { profiles = ["development"], env_set = ["ANDROID_TARGET"] }
command = "cargo"
args = [
  "ndk",
  "--platform",
  "${ANDROID_PLATFORM_VERSION}",
  "--target",
  "${ANDROID_TARGET}",
  "build",
]

[tasks.android-build-release]
private = true
condition = { profiles = ["production"], env_set = ["ANDROID_TARGET"] }
command = "cargo"
args = [
  "ndk",
  "--platform",
  "${ANDROID_PLATFORM_VERSION}",
  "--target",
  "${ANDROID_TARGET}",
  "build",
  "--release"
]

[tasks.android-aarch64]
private = true
condition = { profiles = ["development"] }
env = { ANDROID_TARGET = "aarch64-linux-android" }
run_task = "android-build"

[tasks.android-armv7]
private = true
condition = { profiles = ["development"] }
env = { ANDROID_TARGET = "armv7-linux-androideabi" }
run_task = "android-build"

[tasks.android-i686]
private = true
condition = { profiles = ["development"] }
env = { ANDROID_TARGET = "i686-linux-android" }
run_task = "android-build"

[tasks.android-x86_64]
private = true
condition = { profiles = ["development"] }
env = { ANDROID_TARGET = "x86_64-linux-android" }
run_task = "android-build"

[tasks.android-aarch64-release]
private = true
condition = { profiles = ["production"] }
env = { ANDROID_TARGET = "aarch64-linux-android" }
run_task = "android-build-release"

[tasks.android-armv7-release]
private = true
condition = { profiles = ["production"] }
env = { ANDROID_TARGET = "armv7-linux-androideabi" }
run_task = "android-build-release"

[tasks.android-i686-release]
private = true
condition = { profiles = ["production"] }
env = { ANDROID_TARGET = "i686-linux-android" }
run_task = "android-build-release"

[tasks.android-x86_64-release]
private = true
condition = { profiles = ["production"] }
env = { ANDROID_TARGET = "x86_64-linux-android" }
run_task = "android-build-release"
