on: [push, pull_request]

name: iOS

jobs:
  ci:
    name: Compile and Release
    runs-on: macos-latest
    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm/10.0
          key: ${{ runner.os }}-cached-llvm-10.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm/10.0
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        id: rust_toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: false
          components: rustfmt

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ steps.rust_toolchain.outputs.rustc_hash }}

      - name: Install Cargo Tools (cargo-make)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: cargo-make

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Run cargo make native (Debug)
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: -p development native

      - name: Run Native Tests (in Flutter)
        run: flutter test

      - name: Install iOS Targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Run cargo make ios (Release)
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: -p production ios

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mv target/universal/release/libowlchat_crypto.a target/libowlchat_crypto_universal_apple_ios.a
          mv ffi/binding.h target/owlchat_crypto.h

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          files: |
            target/libowlchat_crypto_universal_apple_ios.a
            target/owlchat_crypto.h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
